bibParser: test/ParserStateTest.cpp File Reference
ParserStateTest.cpp File Reference
#include <gtest/gtest.h>
#include <ParserState.hpp>
#include <BibElement.hpp>
#include <ParserException.hpp>
#include <GlobalParserState.hpp>
#include <StyleParserState.hpp>
#include <KeyParserState.hpp>
#include <ValueParserState.hpp>
#include <IdentifierParserState.hpp>
Classes
class ParserStateTest
Functions
template<class D , class S >
bool isType (const S *src)
TEST_F (ParserStateTest, globalStateIgnoresEverythingButAt)
TEST_F (ParserStateTest, globalStateSwitchesToStyleAtAt)
TEST_F (ParserStateTest, styleParserStateFailsWithWhitespace)
TEST_F (ParserStateTest, styleParserStateDontFailOnCorrectStyle)
TEST_F (ParserStateTest, styleParserStateSwitchesToIdentifierStateOnBrace)
TEST_F (ParserStateTest, globalStateCanGoToIdentifierState)
TEST_F (ParserStateTest, identifierCantContainWhitespace)
TEST_F (ParserStateTest, identifierEndsAtCommaAndIsSaved)
TEST_F (ParserStateTest, keyStateIgnoresTrailingWhitespace)
TEST_F (ParserStateTest, keyStateExitsOnEqualSignAndTrimsKey)
TEST_F (ParserStateTest, valueStateTrimsWhitespaceAndExitsToKeyState)
TEST_F (ParserStateTest, valueStateExitsOnCommaAndMatchingBraces)
TEST_F (ParserStateTest, keyStateExitsToGlobalStateOnClosingBrace)
TEST_F (ParserStateTest, valueStateExitsToGlobalStateOnClosingBrace)
TEST_F (ParserStateTest, canParseFullElement)
TEST_F (ParserStateTest, canParseMultipleElements)
Function Documentation
isType()
template<class D , class S > bool isType (const S * src)
Examples
/github/workspace/test/ParserStateTest.cpp.
Definition at line 14 of file ParserStateTest.cpp.
TEST_F() [1/16]
TEST_F (ParserStateTest , canParseFullElement)
Definition at line 245 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [2/16]
TEST_F (ParserStateTest , canParseMultipleElements)
Definition at line 276 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [3/16]
TEST_F (ParserStateTest , globalStateCanGoToIdentifierState)
Definition at line 110 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [4/16]
TEST_F (ParserStateTest , globalStateIgnoresEverythingButAt)
Definition at line 34 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [5/16]
TEST_F (ParserStateTest , globalStateSwitchesToStyleAtAt)
Definition at line 52 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [6/16]
TEST_F (ParserStateTest , identifierCantContainWhitespace)
Definition at line 125 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [7/16]
TEST_F (ParserStateTest , identifierEndsAtCommaAndIsSaved)
Definition at line 138 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [8/16]
TEST_F (ParserStateTest , keyStateExitsOnEqualSignAndTrimsKey)
Definition at line 168 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [9/16]
TEST_F (ParserStateTest , keyStateExitsToGlobalStateOnClosingBrace)
Definition at line 216 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [10/16]
TEST_F (ParserStateTest , keyStateIgnoresTrailingWhitespace)
Definition at line 154 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [11/16]
TEST_F (ParserStateTest , styleParserStateDontFailOnCorrectStyle)
Definition at line 80 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [12/16]
TEST_F (ParserStateTest , styleParserStateFailsWithWhitespace)
Definition at line 67 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [13/16]
TEST_F (ParserStateTest , styleParserStateSwitchesToIdentifierStateOnBrace)
Definition at line 94 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [14/16]
TEST_F (ParserStateTest , valueStateExitsOnCommaAndMatchingBraces)
Definition at line 200 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [15/16]
TEST_F (ParserStateTest , valueStateExitsToGlobalStateOnClosingBrace)
Definition at line 230 of file ParserStateTest.cpp.
References ParserState::handleCharacter().
TEST_F() [16/16]
TEST_F (ParserStateTest , valueStateTrimsWhitespaceAndExitsToKeyState)
Definition at line 184 of file ParserStateTest.cpp.
References ParserState::handleCharacter().