btool: test/ParserStateFixtureTest.cpp File Reference
ParserStateFixtureTest.cpp File Reference
#include <gtest/gtest.h>
#include <ParserState.hpp>
#include <BibElement.hpp>
#include <ParserException.hpp>
#include <GlobalParserState.hpp>
#include <StyleParserState.hpp>
#include <KeyParserState.hpp>
#include <ValueParserState.hpp>
#include <IdentifierParserState.hpp>
Classes
class ParserStateFixtureTest
Functions
template<class D , class S >
bool isType (const S *src)
TEST_F (ParserStateFixtureTest, globalStateIgnoresEverythingButAt)
TEST_F (ParserStateFixtureTest, globalStateSwitchesToStyleAtAt)
TEST_F (ParserStateFixtureTest, styleParserStateFailsWithWhitespace)
TEST_F (ParserStateFixtureTest, styleParserStateDontFailOnCorrectStyle)
TEST_F (ParserStateFixtureTest, styleParserStateSwitchesToIdentifierStateOnBrace)
TEST_F (ParserStateFixtureTest, globalStateCanGoToIdentifierState)
TEST_F (ParserStateFixtureTest, identifierCantContainWhitespace)
TEST_F (ParserStateFixtureTest, identifierEndsAtCommaAndIsSaved)
TEST_F (ParserStateFixtureTest, keyStateIgnoresTrailingWhitespace)
TEST_F (ParserStateFixtureTest, keyStateExitsOnEqualSignAndTrimsKey)
TEST_F (ParserStateFixtureTest, valueStateTrimsWhitespaceAndExitsToKeyState)
TEST_F (ParserStateFixtureTest, valueStateExitsOnCommaAndMatchingBraces)
TEST_F (ParserStateFixtureTest, keyStateExitsToGlobalStateOnClosingBrace)
TEST_F (ParserStateFixtureTest, valueStateExitsToGlobalStateOnClosingBrace)
TEST_F (ParserStateFixtureTest, canParseFullElement)
TEST_F (ParserStateFixtureTest, canParseMultipleElements)
Function Documentation
isType()
template<class D , class S > bool isType (const S * src)
Examples
/github/workspace/test/ParserStateFixtureTest.cpp.
Definition at line 14 of file ParserStateFixtureTest.cpp.
TEST_F() [1/16]
TEST_F (ParserStateFixtureTest , canParseFullElement)
Definition at line 245 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [2/16]
TEST_F (ParserStateFixtureTest , canParseMultipleElements)
Definition at line 276 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [3/16]
TEST_F (ParserStateFixtureTest , globalStateCanGoToIdentifierState)
Definition at line 110 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [4/16]
TEST_F (ParserStateFixtureTest , globalStateIgnoresEverythingButAt)
Definition at line 34 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [5/16]
TEST_F (ParserStateFixtureTest , globalStateSwitchesToStyleAtAt)
Definition at line 52 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [6/16]
TEST_F (ParserStateFixtureTest , identifierCantContainWhitespace)
Definition at line 125 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [7/16]
TEST_F (ParserStateFixtureTest , identifierEndsAtCommaAndIsSaved)
Definition at line 138 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [8/16]
TEST_F (ParserStateFixtureTest , keyStateExitsOnEqualSignAndTrimsKey)
Definition at line 168 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [9/16]
TEST_F (ParserStateFixtureTest , keyStateExitsToGlobalStateOnClosingBrace)
Definition at line 216 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [10/16]
TEST_F (ParserStateFixtureTest , keyStateIgnoresTrailingWhitespace)
Definition at line 154 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [11/16]
TEST_F (ParserStateFixtureTest , styleParserStateDontFailOnCorrectStyle)
Definition at line 80 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [12/16]
TEST_F (ParserStateFixtureTest , styleParserStateFailsWithWhitespace)
Definition at line 67 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [13/16]
TEST_F (ParserStateFixtureTest , styleParserStateSwitchesToIdentifierStateOnBrace)
Definition at line 94 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [14/16]
TEST_F (ParserStateFixtureTest , valueStateExitsOnCommaAndMatchingBraces)
Definition at line 200 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [15/16]
TEST_F (ParserStateFixtureTest , valueStateExitsToGlobalStateOnClosingBrace)
Definition at line 230 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().
TEST_F() [16/16]
TEST_F (ParserStateFixtureTest , valueStateTrimsWhitespaceAndExitsToKeyState)
Definition at line 184 of file ParserStateFixtureTest.cpp.
References ParserState::handleCharacter().