btool: AbstractGenerator Class Reference
AbstractGenerator Class Reference
#include <AbstractGenerator.hpp>
Public Member Functions
AbstractGenerator (std::vector< BibElement > elements)
Public Member Functions inherited from Generator
virtual ~Generator ()=default
Static Public Member Functions
static auto uniqueFieldsOf (const std::vector< BibElement > &values) noexcept -> std::unordered_set< std::string >
static auto sortedKeys (const std::unordered_set< std::string > &set) noexcept -> std::vector< std::string >
Protected Member Functions
virtual auto fail (const std::string &message, const std::string &type="unknown") -> void
auto write () -> std::string override
Protected Attributes
std::vector< BibElement > elements
Elements to write.
Detailed Description
Abstract Class with default-implementation of a File-Writer
Definition at line 14 of file AbstractGenerator.hpp.
Constructor & Destructor Documentation
AbstractGenerator()
AbstractGenerator::AbstractGenerator (std::vector< BibElement > elements) explicit
Constructor.
Parameters
elements the elements to write
Definition at line 23 of file AbstractGenerator.cpp.
References elements.
Member Function Documentation
fail()
auto AbstractGenerator::fail (const std::string & message, const std::string & type = "unknown") -> void protected virtual
Helper Method to construct sufficient error-messages
Parameters
message the message to use
Exceptions
FileWriterException (always)
Reimplemented in HtmlGenerator, XmlGenerator, and PlainTextGenerator.
Definition at line 12 of file AbstractGenerator.cpp.
Referenced by PlainTextGenerator::fail(), XmlGenerator::fail(), and HtmlGenerator::fail().
sortedKeys()
auto AbstractGenerator::sortedKeys (const std::unordered_set< std::string > & set) -> std::vector<std::string> static noexcept
Sorts a unordered Set of keys into a vector
Parameters
set the unordered set of keys
Returns
the sorted vector of keys
Definition at line 55 of file AbstractGenerator.cpp.
References set().
uniqueFieldsOf()
auto AbstractGenerator::uniqueFieldsOf (const std::vector< BibElement > & values) -> std::unordered_set<std::string> static noexcept
Examples
/github/workspace/test/GeneratorFixtureTest.cpp.
Definition at line 33 of file AbstractGenerator.cpp.
References BibElement::attributes.
Referenced by TEST_F().
write()
auto AbstractGenerator::write () -> std::string override protected virtual
Default write-behaviour (do nothing)
Returns
the elements in target format
Implements Generator.
Reimplemented in HtmlGenerator, XmlGenerator, and PlainTextGenerator.
Definition at line 29 of file AbstractGenerator.cpp.
Member Data Documentation
elements
std::vector<BibElement> AbstractGenerator::elements protected
Elements to write.
Definition at line 16 of file AbstractGenerator.hpp.
Referenced by AbstractGenerator(), HtmlGenerator::HtmlGenerator(), PlainTextGenerator::PlainTextGenerator(), and XmlGenerator::XmlGenerator().
The documentation for this class was generated from the following files:
src/AbstractGenerator.hpp
src/AbstractGenerator.cpp