btool: main.cpp File Reference
main.cpp File Reference
#include <boost/program_options.hpp>
#include <GeneratorException.hpp>
#include <PlainTextGenerator.hpp>
#include <HtmlGenerator.hpp>
#include <XmlGenerator.hpp>
#include <Parser.hpp>
#include <optional>
#include <iostream>
#include <vector>
#include <string>
Classes
struct Conflicts
struct Dependencies
struct Requirements
Functions
void parseCommandLine (int argc, char **argv, po::variables_map &vm, po::options_description &description)
void checkConstraints (const po::variables_map &vm)
int main (int argc, char **argv)
Function Documentation
checkConstraints()
void checkConstraints (const po::variables_map & vm)
Defines all argument constraints and checks them
Parameters
vm the program arguments
Exceptions
std::logic_error when any constraint is violated
Definition at line 138 of file main.cpp.
Referenced by main().
main()
int main (int argc, char ** argv)
Main Program - Resolves command-line-arguments and prints output
Parameters
argc number of command-line arguments
argv command-line arguments
Returns
program exit-code
Definition at line 158 of file main.cpp.
References checkConstraints(), Parser::generate(), parseCommandLine(), HtmlGenerator::write(), PlainTextGenerator::write(), and XmlGenerator::write().
parseCommandLine()
void parseCommandLine (int argc, char ** argv, po::variables_map & vm, po::options_description & description)
Defines CLI and translates program arguments
Parameters
argc the number of program arguments
argv the program arguments
vm[out] the variables map to store command-line-parameters into
description[out] the cli description to populate
Definition at line 103 of file main.cpp.
Referenced by main().