btool: PlainTextGenerator Struct Reference
PlainTextGenerator Struct Reference
#include <PlainTextGenerator.hpp>
Public Member Functions
auto fail (const std::string &message, const std::string &type) -> void override
auto write () -> std::string override
PlainTextGenerator (const std::vector< BibElement > &elements)
Public Member Functions inherited from AbstractGenerator
AbstractGenerator (std::vector< BibElement > elements)
Public Member Functions inherited from Generator
virtual ~Generator ()=default
Additional Inherited Members
Static Public Member Functions inherited from AbstractGenerator
static auto uniqueFieldsOf (const std::vector< BibElement > &values) noexcept -> std::unordered_set< std::string >
static auto sortedKeys (const std::unordered_set< std::string > &set) noexcept -> std::vector< std::string >
Protected Attributes inherited from AbstractGenerator
std::vector< BibElement > elements
Elements to write.
Detailed Description
Examples
/github/workspace/test/GeneratorFixtureTest.cpp.
Definition at line 6 of file PlainTextGenerator.hpp.
Constructor & Destructor Documentation
PlainTextGenerator()
PlainTextGenerator::PlainTextGenerator (const std::vector< BibElement > & elements) explicit
Definition at line 32 of file PlainTextGenerator.cpp.
References AbstractGenerator::elements.
Member Function Documentation
fail()
auto PlainTextGenerator::fail (const std::string & message, const std::string & type) -> void override virtual
Throws a HTML-Generator-Exception
Parameters
message the message to append
Reimplemented from AbstractGenerator.
Definition at line 28 of file PlainTextGenerator.cpp.
References AbstractGenerator::fail().
write()
auto PlainTextGenerator::write () -> std::string override virtual
Writes all elements as plain text
Returns
the written output as String
Exceptions
FileWriterException on error
Reimplemented from AbstractGenerator.
Examples
/github/workspace/test/GeneratorFixtureTest.cpp.
Definition at line 9 of file PlainTextGenerator.cpp.
Referenced by main(), and TEST_F().
The documentation for this struct was generated from the following files:
src/PlainTextGenerator.hpp
src/PlainTextGenerator.cpp