btool: XmlGenerator Struct Reference
XmlGenerator Struct Reference
#include <XmlGenerator.hpp>
Public Member Functions
auto fail (const std::string &message, const std::string &type) -> void override
auto write () -> std::string override
XmlGenerator (const std::vector< BibElement > &elements)
Public Member Functions inherited from AbstractGenerator
AbstractGenerator (std::vector< BibElement > elements)
Public Member Functions inherited from Generator
virtual ~Generator ()=default
Additional Inherited Members
Static Public Member Functions inherited from AbstractGenerator
static auto uniqueFieldsOf (const std::vector< BibElement > &values) noexcept -> std::unordered_set< std::string >
static auto sortedFields (const std::vector< Field > &set) noexcept -> std::vector< Field >
Protected Attributes inherited from AbstractGenerator
std::vector< BibElement > elements
Elements to write.
Detailed Description
XML-Generator
Examples
/github/workspace/test/GeneratorFixtureTest.cpp.
Definition at line 9 of file XmlGenerator.hpp.
Constructor & Destructor Documentation
XmlGenerator()
XmlGenerator::XmlGenerator (const std::vector< BibElement > & elements) explicit
Constructor.
Parameters
elements the elements to write.
Definition at line 8 of file XmlGenerator.cpp.
References AbstractGenerator::elements.
Member Function Documentation
fail()
auto XmlGenerator::fail (const std::string & message, const std::string & type) -> void override virtual
Throws a XML-Generator-Exception
Parameters
message the message to append
Reimplemented from AbstractGenerator.
Definition at line 38 of file XmlGenerator.cpp.
References AbstractGenerator::fail().
write()
auto XmlGenerator::write () -> std::string override virtual
Writes all elements in XML-Format
Returns
the written output as String
Exceptions
FileWriterException on error
Reimplemented from AbstractGenerator.
Examples
/github/workspace/test/GeneratorFixtureTest.cpp.
Definition at line 15 of file XmlGenerator.cpp.
Referenced by main(), and TEST_F().
The documentation for this struct was generated from the following files:
src/XmlGenerator.hpp
src/XmlGenerator.cpp