btool: HtmlGenerator Struct Reference
HtmlGenerator Struct Reference
#include <HtmlGenerator.hpp>
Public Types
enum HtmlTag {
HtmlTag::TABLE, HtmlTag::TABLE_BODY, HtmlTag::TABLE_HEADING, HtmlTag::TABLE_ENTRY,
HtmlTag::TABLE_ROW, HtmlTag::LINK, HtmlTag::SCRIPT, HtmlTag::META,
HtmlTag::TITLE, HtmlTag::H1, HtmlTag::H5, HtmlTag::DIV,
HtmlTag::BUTTON
}
Public Member Functions
auto fail (const std::string &message, const std::string &type="HTML") -> void override
auto write () -> std::string override
auto fillContainer (CTML::Node &parent, const std::vector< std::string > keys) noexcept -> void
auto appendCard (CTML::Node &parent, const BibElement &element, const std::vector< std::string > keys) noexcept -> void
auto appendTable (CTML::Node &parent, const BibElement &element, const std::vector< std::string > keys) noexcept -> void
HtmlGenerator (const std::vector< BibElement > &elements)
Public Member Functions inherited from AbstractGenerator
AbstractGenerator (const std::vector< BibElement > &elements)
Public Member Functions inherited from Generator
virtual ~Generator ()=default
Static Public Member Functions
static auto sortedKeys (const std::unordered_set< std::string > &set) noexcept -> std::vector< std::string >
Static Public Member Functions inherited from AbstractGenerator
static auto uniqueFieldsOf (const std::vector< BibElement > &values) noexcept -> std::unordered_set< std::string >
Additional Inherited Members
Protected Attributes inherited from AbstractGenerator
std::vector< BibElement > elements
Elements to write.
Detailed Description
HTML-Generator
Examples
/github/workspace/test/GeneratorFixtureTest.cpp.
Definition at line 11 of file HtmlGenerator.hpp.
Member Enumeration Documentation
HtmlTag
enum HtmlGenerator::HtmlTag strong
Enum that contains all known HTML tags.
Enumerator
TABLE
TABLE_BODY
TABLE_HEADING
TABLE_ENTRY
TABLE_ROW
LINK
SCRIPT
META
TITLE
H1
H5
DIV
BUTTON
Definition at line 16 of file HtmlGenerator.hpp.
Constructor & Destructor Documentation
HtmlGenerator()
HtmlGenerator::HtmlGenerator (const std::vector< BibElement > & elements)
Constructor.
Parameters
elements the elements to write.
Definition at line 80 of file HtmlGenerator.cpp.
References AbstractGenerator::elements.
Member Function Documentation
appendCard()
auto HtmlGenerator::appendCard (CTML::Node & parent, const BibElement & element, const std::vector< std::string > keys) -> void noexcept
Creates A Card for an element and appends it to the Parent
Parameters
parent[out] the node the Card gets appended to
element the element to create the Card for
keys all possible Field-Keys (sorted)
Definition at line 104 of file HtmlGenerator.cpp.
References Field::value.
appendTable()
auto HtmlGenerator::appendTable (CTML::Node & parent, const BibElement & element, const std::vector< std::string > keys) -> void noexcept
Appends a table of all Element-Atrributes to a node
Parameters
parent[out] the node to append the table to
element the element to create the table for
keys all possible Field-Keys (sorted)
Definition at line 151 of file HtmlGenerator.cpp.
References Field::value.
fail()
auto HtmlGenerator::fail (const std::string & message, const std::string & type = "HTML") -> void override virtual
Throws a HTML-Generator-Exception
Parameters
message the message to append
Reimplemented from AbstractGenerator.
Definition at line 9 of file HtmlGenerator.cpp.
References AbstractGenerator::fail().
fillContainer()
void HtmlGenerator::fillContainer (CTML::Node & parent, const std::vector< std::string > keys) -> void noexcept
Fills the Main Container-Div of the Page-Body
Parameters
parent[out] The Parent node (Container-Div)
keys all the Field-Keys to handle (sorted)
Definition at line 87 of file HtmlGenerator.cpp.
sortedKeys()
auto HtmlGenerator::sortedKeys (const std::unordered_set< std::string > & set) -> std::vector<std::string> static noexcept
Sorts a unordered Set of keys into a vector
Parameters
set the unordered set of keys
Returns
the sorted vector of keys
Definition at line 177 of file HtmlGenerator.cpp.
References set().
write()
auto HtmlGenerator::write () -> std::string override virtual
Writes all elements as HTML-Document (wrapped by Bootstrap)
Returns
the written document as String
Exceptions
FileWriterException on error
Reimplemented from AbstractGenerator.
Definition at line 18 of file HtmlGenerator.cpp.
Referenced by main().
The documentation for this struct was generated from the following files:
src/HtmlGenerator.hpp
src/HtmlGenerator.cpp